In [2]:
import numpy as np 
import pandas as pd

In [7]:
df = pd.read_csv("C:/Users/HP WORLD ANAND/Desktop/Data Science Career/Internship/Codsoft/Task 3/spam.csv",encoding='ISO-8859-1')

In [8]:
df.sample(5)

v1                                                 v2 Unnamed: 2  \
942   spam  How about getting in touch with folks waiting ...        NaN   
338    ham                             Sorry, I'll call later        NaN   
1747   ham                   I think u have the wrong number.        NaN   
4729   ham  I dont know ask to my brother. Nothing problem...        NaN   
1149   ham                             Not a drop in the tank        NaN   

     Unnamed: 3 Unnamed: 4  
942         NaN        NaN  
338         NaN        NaN  
1747        NaN        NaN  
4729        NaN        NaN  
1149        NaN        NaN

## Data Cleaning

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


In [10]:
df.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], inplace=True)

In [11]:
df.sample(2)

v1                                                 v2
779   ham                            That means get the door
3561  ham  Still chance there. If you search hard you wil...

In [12]:
df.rename(columns={'v1':'target', 'v2': 'text'}, inplace=True)
df.sample(2)

target                                               text
3560   spam  Text BANNEDUK to 89555 to see! cost 150p texto...
4777    ham  U R THE MOST BEAUTIFUL GIRL IVE EVER SEEN. U R...

In [13]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

df['target'] = encoder.fit_transform(df['target'])

In [14]:
df.head()

target                                               text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [15]:
df.duplicated().sum()

403

In [16]:
df.drop_duplicates(keep='first', inplace=True)

In [17]:
df.shape

(5169, 2)

In [18]:
df['target'].value_counts()

target
0    4516
1     653
Name: count, dtype: int64

In [20]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')

df['num_characters'] = df['text'].apply(len)

# Calculate the number of words in each SMS using NLTK tokenizer and add as a new column
df['num_words'] = df['text'].apply(lambda x: len(nltk.word_tokenize(x)))

# Calculate the number of sentences in each SMS using NLTK tokenizer and add as a new column
df['num_sentences'] = df['text'].apply(lambda x: len(nltk.sent_tokenize(x)))
df.head()

[nltk_data] Downloading package punkt to C:\Users\HP WORLD
[nltk_data]     ANAND\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\HP WORLD
[nltk_data]     ANAND\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


target                                               text  num_characters  \
0       0  Go until jurong point, crazy.. Available only ...             111   
1       0                      Ok lar... Joking wif u oni...              29   
2       1  Free entry in 2 a wkly comp to win FA Cup fina...             155   
3       0  U dun say so early hor... U c already then say...              49   
4       0  Nah I don't think he goes to usf, he lives aro...              61   

   num_words  num_sentences  
0         24              2  
1          8              2  
2         37              2  
3         13              1  
4         15              1

## Vectorizing Text Data Using TfidfVectorizer(TF-IDF)

In [25]:
df.head()

target                                               text  num_characters  \
0       0  Go until jurong point, crazy.. Available only ...             111   
1       0                      Ok lar... Joking wif u oni...              29   
2       1  Free entry in 2 a wkly comp to win FA Cup fina...             155   
3       0  U dun say so early hor... U c already then say...              49   
4       0  Nah I don't think he goes to usf, he lives aro...              61   

   num_words  num_sentences  
0         24              2  
1          8              2  
2         37              2  
3         13              1  
4         15              1

In [26]:
import string
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps =PorterStemmer()

def transform_text(text):
    text = text.lower()
    text = nltk.word_tokenize(text)

    y = []
    for i in text:
        if i.isalnum():
            y.append(i)
    
    text = y[:]
    y.clear()
    
    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)
    text = y[:]
    y.clear()

    for i in text:
        y.append(ps.stem(i))
    
    return " ".join(y)

In [28]:
transform_text("""Say Every Body
            Our Satguru
            The Love Charger
            True Love Charger
            You are The Love Charger
            You are The Love Charger
            I am so Lucky Because
            You are my Love Charger
            You are The Love Charger
            Billions battery when goes down
            You charged up with Love
            So strong Your Power Love""")

'say everi bodi satguru love charger true love charger love charger love charger lucki love charger love charger billion batteri goe charg love strong power love'

In [30]:
df['transformed_text'] = df['text'].apply(transform_text)
df.head()

target                                               text  num_characters  \
0       0  Go until jurong point, crazy.. Available only ...             111   
1       0                      Ok lar... Joking wif u oni...              29   
2       1  Free entry in 2 a wkly comp to win FA Cup fina...             155   
3       0  U dun say so early hor... U c already then say...              49   
4       0  Nah I don't think he goes to usf, he lives aro...              61   

   num_words  num_sentences                                   transformed_text  
0         24              2  go jurong point crazi avail bugi n great world...  
1          8              2                              ok lar joke wif u oni  
2         37              2  free entri 2 wkli comp win fa cup final tkt 21...  
3         13              1                u dun say earli hor u c alreadi say  
4         15              1               nah think goe usf live around though

In [31]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
cv = CountVectorizer()
tfidf = TfidfVectorizer(max_features= 3000)

X = tfidf.fit_transform(df['transformed_text']).toarray()

In [32]:
X.shape

(5169, 3000)

In [33]:
y = df['target'].values

## Splitting Data into Training and Testing Sets

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=2)

In [35]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score

gnb = GaussianNB()
mnb = MultinomialNB()
bnb = BernoulliNB()

In [36]:
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))

[[788 108]
 [ 27 111]]
0.8694390715667312
0.5068493150684932


In [37]:
mnb.fit(X_train, y_train)
y_pred = mnb.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))

[[896   0]
 [ 30 108]]
0.9709864603481625
1.0


In [38]:
bnb.fit(X_train, y_train)
y_pred = bnb.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))

[[895   1]
 [ 16 122]]
0.9835589941972921
0.991869918699187


### Other Models

In [39]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [41]:
svc = SVC(kernel='sigmoid', gamma=1.0)
lrc = LogisticRegression(solver='liblinear', penalty='l1')

In [42]:
clfs = {
    'SVC' : svc,
    'LRC' : lrc
}

In [43]:
def train_classifier(clf,X_train,y_train,X_test,y_test):
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test,y_pred)
    precision = precision_score(y_test,y_pred)
    
    return accuracy,precision

In [44]:
train_classifier(svc,X_train,y_train,X_test,y_test)

(0.9758220502901354, 0.9747899159663865)

In [45]:
accuracy_scores = []
precision_scores = []

for name, clf in clfs.items():

    current_accuracy,current_precision = train_classifier(clf, X_train,y_train,X_test,y_test)
    print("For ",name)
    print("Accuracy - ",current_accuracy)
    print("Precision - ",current_precision)
    
    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)

For  SVC
Accuracy -  0.9758220502901354
Precision -  0.9747899159663865
For  LRC
Accuracy -  0.9584139264990329
Precision -  0.9702970297029703
